# These are supported funding model platforms

github: utkarshOjha2001
patreon: # 
open_collective: developer-portfolio
ko_fi: #
tidelift: #
community_bridge: #
liberapay: #
issuehunt: #
lfx_crowdfunding: #
polar: #
buy_me_a_coffee: Utkarsh Ojha #
custom: #
